version: "2"
services:
        jackett:
                image: linuxserver/jackett
                container_name: jackett
                environment:
                        - PUID=1000
                        - PGID=1000
                        - TZ=America/New_York

                volumes:
                        - /mnt/Media/docker_apps/jackett/config:/config
                        - /mnt/Media/docker_apps/jackett/downloads:/downloads
                ports:
                        - 9117:9117
                restart: unless-stopped
        sonarr:
                image: linuxserver/sonarr:preview
                container_name: sonarr
                environment:
                        - PUID=1000
                        - PGID=1000
                        - TZ=America/New_York
                volumes:
                        - /mnt/Media/docker_apps/sonarr/config:/config
                        - /mnt/Media/:/mnt/Media
                ports:
                        - 8989:8989
                restart: unless-stopped
        radarr:
                image: linuxserver/radarr
                container_name: radarr
                environment:
                        - PUID=1000
                        - PGID=1000
                        - TZ=America/New_York
                volumes:
                        - /mnt/Media/docker_apps/radarr/config:/config
                        - /mnt/Media/:/mnt/Media
                ports:
                        - 7878:7878
                restart: unless-stopped

        cyberchef:
                image: mpepping/cyberchef
                container_name: cyberchef
                environment:
                        - PUID=1000
                        - GUID=1000
                        - TZ=America/New_York
                ports:
                        - 8000:8000
                restart: unless-stopped
        ombi:
                image: linuxserver/ombi
                container_name: ombi
                environment:
                        - PUID=1000
                        - PGID=1000
                        - TZ=America/New_York
                        #- BASE_URL=/ombi #optional
                volumes:
                        - /mnt/Media/docker_apps/ombi/config:/config
                ports:
                        - 3579:3579
                restart: unless-stopped
        transmission:
               image: haugene/transmission-openvpn
               cap_add:
                       - NET_ADMIN
               devices:
                       - /dev/net/tun
               restart: unless-stopped
               ports:
                       - 9091:9091
               volumes:
                       - /mnt/Media/transmission_data/:/data
                       - /etc/localtime:/etc/localtime:ro
                       - /mnt/Media/complete:/mnt/Media/complete
               environment:
                       - OPENVPN_PROVIDER=PIA
                       - OPENVPN_CONFIG=<region>
                       - OPENVPN_USERNAME=<username>
                       - OPENVPN_PASSWORD=<pass>
                       - WEBPROXY_ENABLED=false
                       - LOCAL_NETWORK=192.168.0.0/24
                       - TRANSMISSION_WEB_UI=combustion
               logging:
                       options:
                               max-size: 10m
