version: "2"
services:
        jackett:
                image: linuxserver/jackett
                container_name: jackett
                environment:
                        - PUID=1000
                        - PGID=1000
                        - TZ=America/New_York

                volumes:
                        - /mnt/Media/docker_apps/jackett/config:/config
                        - /mnt/Media/docker_apps/jackett/downloads:/downloads
                ports:
                        - 9117:9117
                restart: unless-stopped
        sonarr:
                image: linuxserver/sonarr:preview
                container_name: sonarr
                environment:
                        - PUID=1000
                        - PGID=1000
                        - TZ=America/New_York
                volumes:
                        - /mnt/Media/docker_apps/sonarr/config:/config
                        - /mnt/Media/:/mnt/Media
                ports:
                        - 8989:8989
                restart: unless-stopped
        radarr:
                image: linuxserver/radarr
                container_name: radarr
                environment:
                        - PUID=1000
                        - PGID=1000
                        - TZ=America/New_York
                volumes:
                        - /mnt/Media/docker_apps/radarr/config:/config
                        - /mnt/Media/:/mnt/Media
                ports:
                        - 7878:7878
                restart: unless-stopped
